### ISSUE TITLE
Problemi durante installazione

### ISSUE THREAD

**Issue by alemela** [dmm42/LinkHunter#1]
Lanciando `mvn install` si ottiene un rassicurante build success. Ma andando a compliare il .java ottengo:
```
src/LinkHunter.java:16: error: package org.openqa.selenium does not exist
import org.openqa.selenium.WebElement;

src/LinkHunter.java:17: error: package org.openqa.selenium.firefox does not exist
import org.openqa.selenium.firefox.FirefoxDriver;
```
Dal readme non è ben chiaro come installarlo, se è quella parte in cui ti riferisci al classPath di Selenium.

**Comment by dmm42** [comment]
Con `mvn install` lo hai già compilato in automatico. Avevo aggiunto il supporto a Maven ma non avevo aggiornato la documentazione, guarda se ora funziona e se la documentazione è chiara. Attenzione che ho modificato anche _pom.xml_.

**Comment by alemela** [comment]
Ah perfetto!! Ora è tutto chiaro!

Però lancia ancora un'errore:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/firefox/FirefoxDriver
	at LinkHunter.<init>(LinkHunter.java:32)
	at LinkHunter.main(LinkHunter.java:171)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.firefox.FirefoxDriver
```
Cosa può essere?

**Comment by dmm42** [comment]
Mancava il classpath del jar. Se adesso rifai il `mvn package` in target crea anche lib in cui copia tutte le dipendenze. Se sposti il jar altrove sposta anche la directory lib. In alternativa le dipendenze si possono mettere tutte nel jar che diventa di 18 MB.

**Comment by alemela** [comment]
Ora funziona perfettamente, grazie!
