### ISSUE TITLE
log più dicorsivo

### ISSUE THREAD

**Issue by alemela** [dmm42/LinkHunter#4]
Lanciando lo script più volte si hanno comportamenti diversi, credo che un log più discorsivo aiuterebbe a comprendere le differenze.

**Comment by dmm42** [comment]
Fatto, prova a vedere se si capisce qualcosa.

**Comment by alemela** [comment]
Sarebbero utili quelli che hai aggiunto, ma da console non li stampa...

**Comment by dmm42** [comment]
Forse non hai ricompilato, da me li stampa.

**Comment by alemela** [comment]
Un po' di ASCII art non guasterebbe (banalmente un po' di indentazione o di linee) però mi sembra che ci siano tutte le informazioni necessarie per capire se sta lavorando per davvero, se trova qualcosa o nulla, etc.
